# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Tim de Vries'
tagline:          'A collection of ramblings, stumblings and findings for sharing'
description:      'A collection of ramblings, stumblings and findings for sharing'
url:              http://www.devriesitc.com
baseurl:          '/'
paginate:         5

author:
  name:           'Tim de Vries'
  url:            http://www.devriesitc.com

# Custom vars
version:          1.0.0.0

github:
  repo:           https://github.com/timbodv/timbodv.github.io
