# Dependencies
markdown:         redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highligher:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Tim de Vries'
tagline:          'my notepad on the web'
description:      'my notepad on the web'
url:              http://www.devriesitc.com
baseurl:          '/'
paginate:         4

author:
  name:           'Tim de Vries'
  url:            http://www.devriesitc.com

# Custom vars
version:          1.1.0.0

github:
  repo:           https://github.com/timbodv/timbodv.github.io
